"use server";

import { z } from "zod";

const SummarizeDocumentInputSchema = z.object({
  documentText: z
    .string()
    .describe("The complete text content of the document to be summarized."),
});
export type SummarizeDocumentInput = z.infer<typeof SummarizeDocumentInputSchema>;

const SummarizeDocumentOutputSchema = z.object({
  summary: z.string().describe("A concise summary of the input document."),
});
export type SummarizeDocumentOutput = z.infer<typeof SummarizeDocumentOutputSchema>;

export async function summarizeDocument(
  input: SummarizeDocumentInput
): Promise<SummarizeDocumentOutput> {
  // This is a mock implementation of a local AI summarization.
  const summary = `This is a summary generated by a local AI model for the following text: "${input.documentText.substring(0, 100)}..."`;
  
  return new Promise(resolve => {
    setTimeout(() => {
        resolve({ summary });
    }, 1000);
  });
}
